### PR TITLE
small upload fixes

### LINKED ISSUE #198: Data source meta data
at the current front page there are two drop downs for adding meta data to the data set. However, they are disabled and cannot be edited.

image

### LINKED ISSUE #314: Uploading the same dataset twice
In the overview when I upload a file using the file chooser and then try to upload the same file again using the file chooser -> nothing happens. 

possible reason: the `input[type=file]` won't be reseted after the upload thus when selecting the same file again, no `change` event is fired.

### PR DESCRIPTION
**Pull request by sgratzl**
small fixes in the upload page

closes #314, closes #198

image

### CODE REVIEW

File: web/src/components/Upload.vue [hunk 1]
```diff
@@ -6,22 +6,6 @@ import FileList from '@girder/components/src/components/Presentation/FileUploadL
...
-];
-
-const dataTypes = [
-  { name: 'NMR Concentrations', value: 'nmr' },
-  { name: 'conc', value: 'conc' },
-  { name: 'GC/MS', value: 'gcms' },
-  { name: 'LC/MS', value: 'lcms' },
-  { name: 'Other', value: 'other' },
-];
-
```
Comment (subdavis) [inline web/src/components/Upload.vue]: Is this a temporary removal until we can add backend support?  Or did Tom change his mind about wanting this?  Just curious.

Comment (jeffbaumes) [reply web/src/components/Upload.vue]: This is unclear. As far as I am aware it has no analytic value, so this type of information can always be placed in the name/description. I think it's good to remove for now and put it back if/when we know it's needed.

Comment (sgratzl) [reply web/src/components/Upload.vue]: in the end we always have the git history
